# Generated by Django 4.0.4 on 2022-06-06 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.CharField(max_length=200)),
                ('payment_note', models.CharField(blank=True, max_length=500, null=True)),
                ('order_id', models.CharField(blank=True, max_length=500)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=500)),
                ('paid', models.BooleanField(default=False)),
                ('dev_commission', models.IntegerField(default=0)),
                ('paid_to_dev', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient_dev', to='users.profile')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
        ),
    ]
